# Permalinks
#
permalink:           pretty

# Setup
title:               Ráfagas
tagline:             Geospatial links everyday
url:                 http://geoinquiets.github.io/rafagas
paginate:            7
baseurl:             /rafagas

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Geoinquiets
  url:               https://twitter.com/geoinquiets
  email:             jsanz@cartodb.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/geoinquiets/rafagas


gems:                [jekyll-paginate]


defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: Raf