# Permalinks
#
permalink:           /:year/:month-:day.html

# Setup
title:               Ráfagas
tagline:             Geospatial links everyday
site.github.url:     https://geoinquiets.github.io
url:                 https://geoinquiets.github.io
baseurl:             /rafagas

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Geoinquiets
  twitter:           geoinquiets
  url:               https://twitter.com/geoinquiets
  email:             jsanz@cartodb.com


# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/geoinquiets/rafagas

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-sitemap
  - jemoji

jekyll-mentions:
      base_url: https://twitter.com

include:
  - "_pages"

exclude:
  - ".git"
  - "README.md"
  - "LICENSE.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "Rakefile"
  - "vendor"
  - "script"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: Raf
      twitter: geoinquiets
