version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --incremental --port 8000
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - /srv/jekyll/env
      - jekyll:/usr/local/bundle
    ports:
      - '8000:8000'
    environment: 
      RUBYOPT: '-W0'
      JEKYLL_ENV: production 

volumes:
    jekyll:
