name: link-checker
on:
  pull_request:
    branches:
      - gh-pages
jobs:
  link-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install libcurl4-openssl-dev
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.1
          bundler-cache: true

      - name: Cache folders
        uses: actions/cache@v2
        with:
          path: |
            tmp
            _site
          key: ${{ runner.os }}-cache

      - name: Build the site
        run: bundle exec jekyll build
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true

      - name: Run the link check
        id: link-check-run
        run: |
          OUTPUT=$(bundle exec ruby script/proof-all.rb 2>&1 | grep -oP 'External link \K.*+' || true)
          echo "::set-output name=result::$OUTPUT"

      # - name: 'Comment PR'
      #   uses: actions/github-script@0.3.0
      #   if: github.event_name == 'pull_request'
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
      #       github.issues.createComment({ issue_number, owner, repo, body: "```${{ steps.link-check-run.outputs.result }}```" });

      - name: Check outputs
        run: |
          echo ${{ steps.link-check-run.outputs.result }}
          if $(cat ${{ steps.link-check-run.outputs.result }} | wc -l)
          then 
            exit 1
          fi
