name: link-checker
on:
  pull_request:
    branches:
      - gh-pages
jobs:
  link-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install libcurl4-openssl-dev
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.1
          bundler-cache: true

      - name: Cache folders
        uses: actions/cache@v2
        with:
          path: |
            tmp
            _site
          key: ${{ runner.os }}-cache

      - name: Build the site
        run: bundle exec jekyll build
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true

      - name: Run the link check
        id: link-check-run
        run: |
          OUTPUT=$(bundle exec ruby script/proof-all.rb 2>&1 || true)
          OUTPUT="${OUTPUT//'%'/'%25'}​【7,6 m】"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "::set-output name=result::$OUTPUT"

        # - uses: marocchino/sticky-pull-request-comment@v2
        #   with:
        #     header: link-check
        #     message: |
        #       ```
        #       ${{ steps.link-check-run.outputs.result }}
        #       ```

      - name: Check outputs
        run: |
          if echo "${{ steps.link-check-run.outputs.result }}" | grep http
          then 
            exit 1
          fi
