name: Rafagas workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
      - gh-pages
jobs:
  link-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install libcurl4-openssl-dev
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.1
          bundler-cache: true

      - name: Cache folders
        uses: actions/cache@v2
        with:
          path: |
            tmp
            _site
          key: rafagas-cache

      - name: Build the site
        run: bundle exec jekyll build
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true

      - name: Run the link check
        id: link-check-run
        run: |
          bundle exec ruby script/proof-all.rb 2>&1 | tee output.log || true
          echo "::set-output name=count::$(cat output.log | tail -n1)"

      - name: Add comment to PR
        if: github.event_name == 'pull_request' && github.repository_owner == 'geoinquiets'
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data "{ \"body\": \"${{ steps.link-check-run.outputs.count }}\n\n Check the `Run the link check` step output at ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}?check_suite_focus=true\"}"


