name: Rafagas workflow
on:
  pull_request:
    branches:
      - gh-pages
jobs:
  link-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install libcurl4-openssl-dev
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.1
          bundler-cache: true

      - name: Cache folders
        uses: actions/cache@v2
        with:
          path: |
            tmp
            _site
          key: ${{ runner.os }}-cache

      - name: Build the site
        run: bundle exec jekyll build
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true

      - name: Run the link check
        id: link-check-run
        run: |
          bundle exec ruby script/proof-all.rb 2>&1 | grep -oP 'External link \K.*+' > output.log || true
          echo "::set-output name=result::$(cat output.log)"

      - name: Check outputs
        run: |
          echo output.log
          if [ $(cat output.log | wc -l) -ne 0 ] 
          then
            exit 1
          fi
