name: Rafagas workflow
on:
  pull_request:
    branches:
      - gh-pages
jobs:
  link-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install libcurl4-openssl-dev
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.1
          bundler-cache: true

      - name: Cache folders
        uses: actions/cache@v2
        with:
          path: |
            tmp
            _site
          key: rafagas-cache

      - name: Build the site
        run: bundle exec jekyll build
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true

      - name: Run the link check
        id: link-check-run
        run: |
          bundle exec ruby script/proof-all.rb 2>&1 | grep -oP 'External link \K.*+' >> output.log || true
          RESULT=$(cat output.log | wc -l)
          echo "::set-output name=result::$RESULT"

      # - name: 'Comment PR'
      #   uses: actions/github-script@0.3.0
      #   if: github.event_name == 'pull_request'
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
      #       github.issues.createComment({ 
      #         issue_number, 
      #         owner, 
      #         repo, 
      #         body: "Broken links: ${{ steps.link-check-run.outputs.result }}" });
      
      - name: Add comment to PR
        if: github.event_name == 'pull_request'
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OUTPUT=$(cat output.log)
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "```${OUTPUT}```" }'

      # - name: Check outputs
      #   run: |
      #     cat output.log
      #     if [ ${{ steps.link-check-run.outputs.result }} -ne 0 ] 
      #     then
      #       exit 1
      #     fi
